#!/usr/bin/perl


## Script written by Noah Guttman and Copyright (C) 2011 Noah Guttman. This script is released and distributed under the terms of the GNU General Public License

#Libraries to use
use strict;
use Getopt::Std;

use vars qw($opt_w $opt_c $opt_M $opt_h);

my $returnmessage = " ";

my $resulttype="";
my $port1="";
my $port2="";

my @gah;
my $i;

my $checkresult;

##init();

# Get the options
if ($#ARGV le 0) {

} else {
	getopts('hc:M:w:');
}


## Display Help
if ($opt_h){
	print "::SRP Check Instructions::\n\n";
        print " -h,             Display this help information\n";
        print " -w,             More than this many calls returns a warning\n";
        print "                  The default is 600\n";
        print " -c,             More than this many calls returns a critical\n";
        print "                  The default is 800\n";
        print " -M,             Specify a message to return on failure\n";
        print "Script written by Noah Guttman and Copyright (C) 2011 Noah Guttman.\n";
        print "This script is released and distributed under the terms of the GNU\n";
        print "General Public License.     >>>>    http://www.gnu.org/licenses/\n";
        print "";
        print "This program is free software: you can redistribute it and/or modify\n";
        print "it under the terms of the GNU General Public License as published by\n";
        print "the Free Software Foundation.\n\n";
        print "This program is distributed in the hope that it will be useful,\n";
        print "but WITHOUT ANY WARRANTY; without even the implied warranty of\n";
        print "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n";
        print "GNU General Public License for more details.\n";
        print ">>>>    http://www.gnu.org/licenses/\n";
        exit 0; 
}

##Set custom output if any set
if ($opt_M){
	$returnmessage=$opt_M;
}else{
	$returnmessage="";
}
if ($opt_w){
# somthing
}else{
	$opt_w = 600;
}
if ($opt_c){
# somthing
}else{
	$opt_c = 800;
}

#run the check
$checkresult = ((`/usr/sbin/lsof -i |grep rtpproxy |grep -c UDP`)/4);
if ($checkresult > $opt_c){
	print ("CRITICAL: Dangerous call levels - Quality may be impacted: $returnmessage $checkresult|calls=$checkresult;;;;\n");
        exit 2;
}elsif ($checkresult > $opt_w){
        print ("WARNING: Dangerous call levels: $returnmessage $checkresult|calls=$checkresult;;;;\n");
        exit 1;
}else{
        print ("OK: Calls within allowed ranges: $checkresult|calls=$checkresult;;;;\n");
        exit 0;
}
# Code should never get this far, but just in case....
print ("Something has gone wrong\n");
exit 3;
